### ISSUE TITLE
low level API

### ISSUE THREAD

**Issue by inf3rno** [inf3rno/e2e#5]
I thought of something similar to nightwatch, but with async-await. In their example code there is something like this:

```js
module.exports = {
  'Demo test Google' : function (client) {
    client
      .url('http://www.google.com')
      .waitForElementVisible('body', 1000)
      .assert.title('Google')
      .assert.visible('input[type=text]')
      .setValue('input[type=text]', 'rembrandt van rijn')
      .waitForElementVisible('button[name=btnG]', 1000)
      .click('button[name=btnG]')
      .pause(1000)
      .assert.containsText('ol#rso li:first-child',
        'Rembrandt - Wikipedia')
      .end();
  }
};
```

- [x] #6  - we need an interface for navigation. we need to decide whether we allow application initiated navigation and/or user initiated one and what to do about it on the api level
- [x] #9  - we need to decide about which navigation events we care about (loading, dom loaded, uri set, uri hash set, etc.) 
- [x] #10 - we need an interface to check whether an event, for example a navigation event happened. but tbh. it could be any other event
- [x] #14 - we need an interface to trigger events, fill forms on the actual page. ofc there is already an interface for that fireEvent, etc, but we should make it simpler I think
- [x] #15  - we need a clock, or some kind of api to pause for a sec, do we? no we don't.

**Comment by inf3rno** [comment]
What I'd like to do looks like this:

```js
const client = require("myAppClient");
const expect = require("expect.js");

beforeEach(async function (){
	await client.clear();
});

describe("Google", function() {
    it("finds a wikipedia page for the Rembrandt keyword", async function() {
		const doc = await client.load("http://www.google.com");
		await client.gettingVisible("body");
		expect(doc.title).to.be("Google");
		const input = client.find("input[type=text]");
		expect(client.isVisible(input)).to.be.ok(); 
		client.fill(input, "rembrandt van rijn");
		await client.gettingVisible("button[name=btnG]");
		await client.tick(1000);
		expect(client.containsText("ol#rso li:first-child", "Rembrandt - Wikipedia");
    });
});
```
I'd rather use jquery or something like that to write and test the values. The only real feature will be navigation: following links and submitting forms. Following links will be interesting, I am not sure I can do that by firing a click event, or I have to write location.href directly. Tbh. I never clicked on a link with js in the past 20 years, and as far as I remember it is not possible to do that directly, but I'll experiment with it.

**Comment by inf3rno** [comment]
const expect = require("expect.js");
const client = require("myAppClient");
const jquery = require("jquery");
const clock = require("clock");

beforeEach(async function (){
	await client.clear();
});

describe("Google", function() {
	it("finds a wikipedia page for the Rembrandt keyword", async function() {
		const doc = await client.navigate("http://www.google.com");
		const $ = client.$;
		await client.poll($ => $("body").is(":visible"));
		expect(doc.attr("title")).to.be("Google");
		const input = $("input[type=text]");
		expect(input.is(":visible")).to.be.ok();
		input.val("rembrandt van rijn");
		await client.poll($ => $("button[name=btnG]").is(":visible"));
		await clock.tick(1000);
		expect($("ol#rso li:first-child:contains('Rembrandt - Wikipedia')").length > 0).to.be.ok();
	});
});

**Comment by inf3rno** [comment]
Let's check the myAppClient:

```js
const E2EClient = require("e2e-client");

const client = new E2EClient({
	baseURI: "http://localhost:3333",
	checkOrigin: true,
	navigationTimeout: 2500,
	pollingTimeout: 1000,
	pollingRate: 10
});
module.exports = client;
```

**Comment by inf3rno** [comment]
Another topic about the mutation observer: https://stackoverflow.com/questions/2157963/is-it-possible-to-listen-to-a-style-change-event

**Comment by inf3rno** [comment]
- [ ] #9  - we need to decide about which navigation events we care about (loading, dom loaded, uri set, uri hash set, etc.) 
- [ ] #10 - we need an API to check whether an event, for example a navigation event happened. but tbh. it could be any other event

**Comment by inf3rno** [comment]
Currently our low level API looks like this:

```js
const expect = require("chai").expect;
const e2e = require("./e2e");
const navigator = e2e.openWindow({
    silent: true
});

describe("cross-origin, cross-frame communication", function () {

    it("should load google.com", async function () {
        const searchPage = await navigator.load("https://www.google.com");
        const searchInput = searchPage.querySelector("input[type=text]");
        expect(searchInput != null).to.equal(true);
        searchInput.value = "rembrandt van rijn";
        const searchForm = searchInput.closest("form");
        const resultsPage = await navigator.submit(searchForm);
        expect(resultsPage.documentElement.innerHTML.indexOf("Rembrandt - Wikipedia") !== -1).to.equal(true);
    });

    after(function () {
        navigator.closeWindow();
    });
});
```

**Comment by inf3rno** [comment]
Later we can extend this with form data support #82 and form data builder #84, but those might be high level features. At least the form data builder.

**Comment by inf3rno** [comment]
The #10 is only partially complete, but we don't need it currently. We have the methods to handle navigation related events with promises, so we can close this. At last.
